[workspace]
channels = ["conda-forge"]
name = "eip_scanner"
platforms = ["linux-64", "win-64", "osx-64", "osx-arm64"]
version = "0.1.0"

[tasks]
build = "mkdir -p build && cd build && cmake ../ -DCMAKE_BUILD_TYPE=RelWithDebInfo -DBUILD_SHARED_LIBS=ON && cmake --build . --parallel --config RelWithDebInfo"
install = "cmake --build . --target install"

[dependencies]
cmake = ">=3.16,<5"
cxx-compiler = ">=1.11.0,<2"

[target.linux-64.dependencies]
lttng-ust = ">=2.13.9,<3"
